encoding: utf-8

# SEO相关信息
title: Ckole Blog
description: ckole
keywords: ckole,sanckole
author: ckole
footerText: 

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'http://ckole.com'
baseurl: ''

# 跳转地址，会在chat页面中重定向到该地址
tucaoUrl: https://ckole.com

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
menu:
  - title: Homepage
    url: /
  - title: Categorization
    url: /pages/categories.html
  - title: Search
    url: /pages/search.html
  - title: Links
    url: /pages/links.html
  - title: Guestbook
    url: /pages/chat.html
  - title: About
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 显示访问量统计，由不蒜子提供服务
extCount: true

# 友情链接
links:
  - title: github
    url: https://github.com